LIST P=16F877A
INCLUDE <P16F877A.INC>
__CONFIG _CP_OFF &_WDT_OFF &_HS_OSC &_PWRTE_OFF &_LVP_OFF

;Bu uygulama bir dijital olarak sayaç uygulamasýdýr.
;Sayaç 0 dan 9999'a kadar sayma iþlemini display de gösterecek.

SAYI0  EQU 0x20
SAYI1  EQU 0x21
SAYI2  EQU 0x22
TEMP   EQU 0x23
BIRLER EQU 0x24
ONLAR  EQU 0x25
YUZLER EQU 0x26
BINLER EQU 0x27
TEMP1  EQU 0x28
TEMP2  EQU 0x29
TEMP3  EQU 0x2A
TEMP4  EQU 0x2B

    ORG 0
    GOTO START 
    
    ORG 4
    GOTO START 

BANK0 MACRO 
	BCF STATUS,5
	ENDM 
BANK1 MACRO 
	BSF STATUS,5
	ENDM 

START 
	BANK1
	MOVLW B'11110000'
	MOVWF TRISD  ; D portunda 0,1,2 ve 3 output 4,5,6 ve 7 input oldu.
	CLRF  TRISB  ; RB0-RB7 OUTPUT.
    BANK0
    CLRF PORTB
    CLRF PORTD
    MOVLW .0
    MOVWF BINLER
    MOVLW .0
    MOVWF YUZLER 
    MOVLW .0
    MOVWF ONLAR
    MOVLW .0
    MOVWF BIRLER
   
LOOP 
	CALL GOSTER  ; 6 ms zaman alýr.
	CALL TUSTARA ; 6 ms zamanda buradan.
	GOTO LOOP
TUSTARA 
; 1.SATIR TARAMA BAÞLADI.....
	MOVLW B'11110111'
	MOVWF PORTD  ; 1.SATIR SEÇME ÝÞLEMÝ YAPILDI.
	CALL BEKLE ; 1,5 ms bekle.
B1  BTFSC PORTD,4  ;Eðer rd4=0 ise 1 komut atla.
	GOTO B2
	MOVLW .0
	MOVWF ONLAR
	MOVLW .1
	MOVWF BIRLER
	RETURN
B2  BTFSC PORTD,5  ;Eðer rd5=0 ise 1 komut atla.
	GOTO B3
	MOVLW .0
	MOVWF ONLAR
	MOVLW .2
	MOVWF BIRLER
	RETURN
B3  BTFSC PORTD,6  ;Eðer rd6=0 ise 1 komut atla.
	GOTO B4
	MOVLW .0
	MOVWF ONLAR
	MOVLW .3
	MOVWF BIRLER
	RETURN
B4  BTFSC PORTD,7  ;Eðer rd7=0 ise 1 komut atla.
	GOTO B5
	MOVLW .0
	MOVWF ONLAR
	MOVLW .4
	MOVWF BIRLER
	RETURN
; 1. SATIR TARAMA BÝTTÝ....

; 2.SATIR TARAMA BAÞLADI.....
B5	MOVLW B'11111011'
	MOVWF PORTD  ; 2.SATIR SEÇME ÝÞLEMÝ YAPILDI.
	CALL BEKLE ; 1,5 ms bekle.
    BTFSC PORTD,4  ;Eðer rd4=0 ise 1 komut atla.
	GOTO B6
	MOVLW .0
	MOVWF ONLAR
	MOVLW .5
	MOVWF BIRLER
	RETURN
B6  BTFSC PORTD,5  ;Eðer rd5=0 ise 1 komut atla.
	GOTO B7
	MOVLW .0
	MOVWF ONLAR
	MOVLW .6
	MOVWF BIRLER
	RETURN
B7  BTFSC PORTD,6  ;Eðer rd6=0 ise 1 komut atla.
	GOTO B8
	MOVLW .0
	MOVWF ONLAR
	MOVLW .7
	MOVWF BIRLER
	RETURN
B8  BTFSC PORTD,7  ;Eðer rd7=0 ise 1 komut atla.
	GOTO B9
	MOVLW .0
	MOVWF ONLAR
	MOVLW .8
	MOVWF BIRLER
	RETURN
; 2. SATIR TARAMA BÝTTÝ....

; 3.SATIR TARAMA BAÞLADI.....
B9	MOVLW B'11111101'
	MOVWF PORTD  ; 3.SATIR SEÇME ÝÞLEMÝ YAPILDI.
	CALL BEKLE ; 1,5 ms bekle.
    BTFSC PORTD,4  ;Eðer rd4=0 ise 1 komut atla.
	GOTO B10
	MOVLW .0
	MOVWF ONLAR
	MOVLW .9
	MOVWF BIRLER
	RETURN
B10  BTFSC PORTD,5  ;Eðer rd5=0 ise 1 komut atla.
	GOTO B11
	MOVLW .1
	MOVWF ONLAR
	MOVLW .0
	MOVWF BIRLER
	RETURN
B11  BTFSC PORTD,6  ;Eðer rd6=0 ise 1 komut atla.
	GOTO B12
	MOVLW .1
	MOVWF ONLAR
	MOVLW .1
	MOVWF BIRLER
	RETURN
B12  BTFSC PORTD,7  ;Eðer rd7=0 ise 1 komut atla.
	GOTO B13
	MOVLW .1
	MOVWF ONLAR
	MOVLW .2
	MOVWF BIRLER
	RETURN
; 3. SATIR TARAMA BÝTTÝ....

; 4.SATIR TARAMA BAÞLADI.....
B13	MOVLW B'11111110'
	MOVWF PORTD  ; 4.SATIR SEÇME ÝÞLEMÝ YAPILDI.
	CALL BEKLE ; 1,5 ms bekle.
    BTFSC PORTD,4  ;Eðer rd4=0 ise 1 komut atla.
	GOTO B14
	MOVLW .1
	MOVWF ONLAR
	MOVLW .3
	MOVWF BIRLER
	RETURN
B14  BTFSC PORTD,5  ;Eðer rd5=0 ise 1 komut atla.
	GOTO B15
	MOVLW .1
	MOVWF ONLAR
	MOVLW .4
	MOVWF BIRLER
	RETURN
B15  BTFSC PORTD,6  ;Eðer rd6=0 ise 1 komut atla.
	GOTO B16
	MOVLW .1
	MOVWF ONLAR
	MOVLW .5
	MOVWF BIRLER
	RETURN
B16  BTFSC PORTD,7  ;Eðer rd7=0 ise 1 komut atla.
	RETURN          ; HÝÇBÝR BUTON BASILI DEÐÝLSE BURASI ÇALIÞIYOR.
	MOVLW .1
	MOVWF ONLAR
	MOVLW .6
	MOVWF BIRLER
	RETURN
; 4. SATIR TARAMA BÝTTÝ....


GOSTER ; burada seçilen displaylere deðerler gönderiliyor ve
	   ; aktif olan display de sonuç yazdýrýlýyor.
	MOVF BINLER,W ; W = BINLER
	MOVWF PORTD	  ; PORTD = W => DATA BUS = BINLER
	MOVLW B'00000001'
	MOVWF PORTB   ; RB0=1 OLDU BINLER DISPLAY AKTÝF
	CALL BEKLE	  ; 3ms BEKLE
	MOVF YUZLER,W
	MOVWF PORTD
	MOVLW B'00000010'
	MOVWF PORTB
	CALL BEKLE    ; 3ms BEKLE
	MOVF ONLAR,W
	MOVWF PORTD
	MOVLW B'00000100'
	MOVWF PORTB
	CALL BEKLE    ; 3ms BEKLE
	MOVF BIRLER,W
	MOVWF PORTD
	MOVLW B'00001000'
	MOVWF PORTB
	CALL BEKLE    ; 3ms BEKLE
	CLRF PORTB
RETURN


;Programda gecikme yaparak sonucun gözle görülebilir düzeye
;getirilme iþlemleri yapýlýyor.
BEKLE
	MOVLW .50 
	MOVWF SAYI0
BEKLE0 
	MOVLW .50
	MOVWF SAYI1
BEKLE1
	MOVLW .50
	MOVWF SAYI2
BEKLE2
	DECFSZ SAYI2,F
	GOTO BEKLE2
	DECFSZ SAYI1,F
	GOTO BEKLE1
	DECFSZ SAYI0,F
	GOTO BEKLE0
	RETURN
  END
